### ISSUE TITLE
generating default config

### ISSUE THREAD

**Issue by joshiggins** [gpbenton/gerbera#2]
Looks like automatic config generation was removed in https://github.com/gerbera/gerbera/pull/282 so you need to do a

```
docker run -it --rm gerbera_app --create-config > config/config.xml
```

after `docker-compose build` and before your `docker-compose up`.

Otherwise it works great, thanks for sharing! :+1: :wink:

**Comment by gpbenton** [comment]
Thanks for this.  I'll update the documentation.
